"use strict";
const canvas=document.getElementById("game"),ctx=canvas.getContext("2d"),keys=new Set(),W=3000,H=1900;
ctx.imageSmoothingEnabled=false;
const classes={warrior:{name:"Guerrero",hp:140,mp:55,speed:195,atk:20,range:68,skills:["Corte circular","Embestida","Guardia","Furia"]},archer:{name:"Arquero",hp:100,mp:75,speed:225,atk:16,range:190,skills:["Disparo doble","Flecha veloz","Evasión","Lluvia"]},mage:{name:"Mago",hp:85,mp:120,speed:205,atk:24,range:165,skills:["Bola de fuego","Nova","Escudo arcano","Meteorito"]}};
const p={x:540,y:660,r:13,cls:"warrior",hp:140,maxHp:140,mp:55,maxMp:55,speed:195,atk:20,range:68,level:1,xp:0,nextXp:100,gold:25,kills:0};
let inventory=[{name:"Poción menor",type:"potion",qty:2}],equipment={weapon:null,armor:null},questStage=0;
const buildings=[{x:290,y:230,w:320,h:205,roof:"#5b75a4",name:"Posada"},{x:690,y:235,w:270,h:190,roof:"#a85b42",name:"Mercado"},{x:300,y:805,w:265,h:180,roof:"#8a6544",name:"Herrería"},{x:690,y:800,w:290,h:190,roof:"#657a50",name:"Casa del Gremio"}];
const solids=[...buildings.map(b=>({x:b.x,y:b.y+75,w:b.w,h:b.h-75})),{x:495,y:490,w:95,h:95}];
const npcs=[{x:785,y:465,name:"Mira",role:"Mercader",c:"#d9a65c"},{x:430,y:785,name:"Borin",role:"Herrero",c:"#b57b55"},{x:590,y:600,name:"Aldric",role:"Capitán",c:"#d9d3b5"}];
const spawn=[["Slime",900,620,38,15,18,5],["Slime",980,720,38,15,18,5],["Lobo",1120,540,58,18,28,8],["Lobo",1200,780,58,18,28,8],["Goblin",1450,650,82,22,40,14],["Goblin",1540,820,82,22,40,14],["Esqueleto",1800,570,110,27,55,20],["Esqueleto",1880,850,110,27,55,20],["Orco",2150,720,155,34,80,28],["Orco",2300,930,155,34,80,28]];
const enemies=spawn.map(([type,x,y,hp,atk,xp,gold])=>({type,x,y,homeX:x,homeY:y,r:15,hp,maxHp:hp,atk,xp,gold,dead:false,hit:0}));
enemies.push({type:"Rey Goblin",x:1620,y:1250,homeX:1620,homeY:1250,r:25,hp:420,maxHp:420,atk:38,xp:180,gold:100,dead:false,hit:0});
let cam={x:0,y:0},last=performance.now(),cool=[0,0,0,0,0],flash=0,questKills=0;
const shop=[{name:"Poción menor",type:"potion",price:12},{name:"Espada de hierro",type:"weapon",price:65,atk:6},{name:"Arco de cazador",type:"weapon",price:65,atk:6},{name:"Bastón de aprendiz",type:"weapon",price:65,atk:6},{name:"Armadura de cuero",type:"armor",price:80,hp:20}];
function hitSolid(x,y){return solids.some(o=>x+p.r>o.x&&x-p.r<o.x+o.w&&y+p.r>o.y&&y-p.r<o.y+o.h)}
function move(dt){let dx=(keys.has("d")||keys.has("arrowright"))-(keys.has("a")||keys.has("arrowleft")),dy=(keys.has("s")||keys.has("arrowdown"))-(keys.has("w")||keys.has("arrowup"));if(!dx&&!dy)return;let l=Math.hypot(dx,dy);dx=dx/l*p.speed*dt;dy=dy/l*p.speed*dt;let nx=Math.max(p.r,Math.min(W-p.r,p.x+dx));if(!hitSolid(nx,p.y))p.x=nx;let ny=Math.max(p.r,Math.min(H-p.r,p.y+dy));if(!hitSolid(p.x,ny))p.y=ny}
function target(range){let best=null,d0=range;for(const e of enemies){if(e.dead)continue;let d=Math.hypot(e.x-p.x,e.y-p.y);if(d<d0){d0=d;best=e}}return best}
function damage(e,n){if(!e)return;e.hp-=n;e.hit=.12;if(e.hp<=0){e.dead=true;p.xp+=e.xp;p.gold+=e.gold;p.kills++;questKills=Math.min(3,questKills+1);if(questStage===1){questProgress.textContent=questKills+"/3";if(questKills>=3){questStage=2;questText.textContent="Regresa con Aldric [E]";}} if(Math.random()<.35){addItem("Poción menor","potion",1);notify("Botín: Poción menor");}while(p.xp>=p.nextXp){p.xp-=p.nextXp;p.level++;p.nextXp=Math.floor(p.nextXp*1.3);p.maxHp+=12;p.hp=p.maxHp;p.atk+=3}setTimeout(()=>{e.hp=e.maxHp;e.x=e.homeX;e.y=e.homeY;e.dead=false},5000)}hud()}
function useSkill(i){if(cool[i]>0)return;const c=classes[p.cls];if(i===0){cool[i]=.45;flash=.12;damage(target(p.range),p.atk);return}const costs=[0,12,16,20,28];if(p.mp<costs[i])return;p.mp-=costs[i];cool[i]=[0,.9,2.5,5,8][i];let mult=i===1?1.7:i===2?1.35:i===4?2.7:1;if(i===3){p.hp=Math.min(p.maxHp,p.hp+(p.cls==="warrior"?35:22))}else damage(target(p.range+(p.cls==="warrior"?25:70)),p.atk*mult);hud()}
function ai(dt){for(const e of enemies){if(e.dead)continue;e.hit=Math.max(0,e.hit-dt);let d=Math.hypot(p.x-e.x,p.y-e.y);if(d<245&&d>32){e.x+=(p.x-e.x)/d*55*dt;e.y+=(p.y-e.y)/d*55*dt}else if(d<=32&&Math.random()<dt*.8){p.hp-=Math.max(2,e.atk-Math.floor(p.level/2));if(p.hp<=0){p.hp=p.maxHp;p.mp=p.maxMp;p.x=540;p.y=660}hud()}}}
function hud(){hp.max=p.maxHp;hp.value=p.hp;mp.max=p.maxMp;mp.value=p.mp;xp.max=p.nextXp;xp.value=p.xp;level.textContent=p.level;gold.textContent=p.gold;className.textContent=classes[p.cls].name;zone.textContent=p.x<1050?"Aldea de Lumen":p.x<1750?"Bosque Eterno":p.x<2400?"Ruinas de Ceniza":"Tierras Salvajes"}
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x-cam.x),Math.round(y-cam.y),w,h)}
function tree(x,y){rect(x-8,y-4,16,30,"#533921");ctx.fillStyle="#244c2c";ctx.beginPath();ctx.arc(x-cam.x,y-24-cam.y,28,0,7);ctx.fill();ctx.fillStyle="#35683a";ctx.beginPath();ctx.arc(x-10-cam.x,y-32-cam.y,18,0,7);ctx.arc(x+13-cam.x,y-34-cam.y,17,0,7);ctx.fill()}
function house(b){rect(b.x,b.y+55,b.w,b.h-55,"#c4aa79");rect(b.x+12,b.y+75,b.w-24,b.h-90,"#9d845d");ctx.fillStyle=b.roof;ctx.beginPath();ctx.moveTo(b.x-18-cam.x,b.y+70-cam.y);ctx.lineTo(b.x+b.w/2-cam.x,b.y-cam.y);ctx.lineTo(b.x+b.w+18-cam.x,b.y+70-cam.y);ctx.closePath();ctx.fill();rect(b.x+b.w/2-22,b.y+b.h-55,44,55,"#493624");ctx.fillStyle="#f5e3a0";ctx.font="bold 12px serif";ctx.textAlign="center";ctx.fillText(b.name,b.x+b.w/2-cam.x,b.y+b.h+16-cam.y)}
function world(){rect(0,0,W,H,"#4e7439");rect(0,600,W,140,"#b29a67");rect(475,0,145,1080,"#b29a67");rect(245,180,770,870,"#64834a");for(let x=1080;x<1700;x+=150)for(let y=120;y<1500;y+=170)tree(x+(y%3)*12,y);for(let x=2470;x<2950;x+=145)for(let y=100;y<1750;y+=165)tree(x,y);for(const b of buildings)house(b);rect(500,500,85,85,"#527f89");rect(510,510,65,65,"#75a9ad");ctx.fillStyle="#d5c69b";ctx.beginPath();ctx.arc(542-cam.x,542-cam.y,18,0,7);ctx.fill();for(let x=115;x<2400;x+=220){if(x>250&&x<1050)continue;tree(x,180);tree(x,1120)}}
function npc(n){ctx.fillStyle=n.c;ctx.fillRect(n.x-8-cam.x,n.y-20-cam.y,16,22);ctx.fillStyle="#e3bd91";ctx.fillRect(n.x-6-cam.x,n.y-29-cam.y,12,10);ctx.fillStyle="#fff";ctx.font="11px monospace";ctx.textAlign="center";ctx.fillText(n.name+" · "+n.role,n.x-cam.x,n.y-37-cam.y)}
function mob(e){let c={Slime:"#75b54b",Lobo:"#858585",Goblin:"#668b43",Esqueleto:"#d8d1b9",Orco:"#52773d"}[e.type]||"#999";ctx.fillStyle=e.hit?"#fff":c;if(e.type==="Slime"){ctx.beginPath();ctx.ellipse(e.x-cam.x,e.y-cam.y,17,12,0,0,7);ctx.fill()}else{ctx.fillRect(e.x-11-cam.x,e.y-20-cam.y,22,24);ctx.beginPath();ctx.arc(e.x-cam.x,e.y-24-cam.y,e.type==="Orco"?11:9,0,7);ctx.fill()}rect(e.x-20,e.y-38,40,4,"#321");rect(e.x-20,e.y-38,40*e.hp/e.maxHp,4,"#b44");ctx.fillStyle="#fff";ctx.font="11px monospace";ctx.textAlign="center";ctx.fillText(e.type,e.x-cam.x,e.y-44-cam.y)}
function actors(){for(const n of npcs)npc(n);for(const e of enemies)if(!e.dead)mob(e);ctx.fillStyle=flash?"#fff0a8":p.cls==="warrior"?"#4b9bd1":p.cls==="archer"?"#65a85c":"#9b6bd1";ctx.fillRect(p.x-10-cam.x,p.y-20-cam.y,20,25);ctx.fillStyle="#e7c39b";ctx.fillRect(p.x-7-cam.x,p.y-29-cam.y,14,10);ctx.fillStyle="#fff";ctx.font="bold 11px monospace";ctx.textAlign="center";ctx.fillText(classes[p.cls].name,p.x-cam.x,p.y-36-cam.y)}
function loop(t){let dt=Math.min(.035,(t-last)/1000);last=t;move(dt);ai(dt);for(let i=0;i<cool.length;i++)cool[i]=Math.max(0,cool[i]-dt);p.mp=Math.min(p.maxMp,p.mp+3*dt);flash=Math.max(0,flash-dt);cam.x=Math.max(0,Math.min(W-canvas.width,p.x-canvas.width/2));cam.y=Math.max(0,Math.min(H-canvas.height,p.y-canvas.height/2));ctx.clearRect(0,0,canvas.width,canvas.height);world();actors();hud();requestAnimationFrame(loop)}
function choose(k){p.cls=k;const c=classes[k];Object.assign(p,{maxHp:c.hp,hp:c.hp,maxMp:c.mp,mp:c.mp,speed:c.speed,atk:c.atk,range:c.range});document.querySelectorAll(".hotbar [data-skill]").forEach((b,i)=>b.querySelector("span").textContent=i?c.skills[i-1]:"Ataque");classSelect.classList.add("hidden");hud()}
document.querySelectorAll("[data-class]").forEach(b=>b.addEventListener("click",()=>choose(b.dataset.class)));addEventListener("keydown",e=>{let k=e.key.toLowerCase();keys.add(k);if(k===" ")useSkill(0);if(/^[1-4]$/.test(k))useSkill(+k)});addEventListener("keyup",e=>keys.delete(e.key.toLowerCase()));document.querySelectorAll("[data-skill]").forEach(b=>b.addEventListener("click",()=>useSkill(+b.dataset.skill)));document.querySelectorAll("[data-move]").forEach(b=>{let k=b.dataset.move;b.addEventListener("pointerdown",()=>keys.add(k));["pointerup","pointercancel","pointerleave"].forEach(ev=>b.addEventListener(ev,()=>keys.delete(k)))});
hud();requestAnimationFrame(loop);
function notify(t){toast.textContent=t;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),1800)}
function addItem(name,type,qty=1,extra={}){let it=inventory.find(x=>x.name===name);if(it)it.qty=(it.qty||1)+qty;else inventory.push({name,type,qty,...extra});renderInventory()}
function renderInventory(){inventoryList.innerHTML=inventory.length?"":"<p>Mochila vacía.</p>";for(const it of inventory){let d=document.createElement("div");d.className="item";d.innerHTML="<span>"+it.name+" x"+(it.qty||1)+"</span>";let b=document.createElement("button");b.textContent=it.type==="potion"?"Usar":"Equipar";b.onclick=()=>useItem(it);d.appendChild(b);inventoryList.appendChild(d)}eqWeapon.textContent=equipment.weapon?.name||"Ninguna";eqArmor.textContent=equipment.armor?.name||"Ropa de viajero"}
function useItem(it){if(it.type==="potion"){p.hp=Math.min(p.maxHp,p.hp+45);it.qty--;if(it.qty<=0)inventory=inventory.filter(x=>x!==it)}else{equipment[it.type]=it;notify(it.name+" equipado")}renderInventory();hud()}
function buy(it){if(p.gold<it.price){notify("No tienes suficiente oro");return}p.gold-=it.price;addItem(it.name,it.type,1,it);notify("Compraste "+it.name);hud()}
function openShop(n){dialogName.textContent=n.name+" · "+n.role;dialogText.textContent="Bienvenido. Equípate antes de salir de Lumen.";dialogActions.innerHTML="";for(const it of shop){let b=document.createElement("button");b.textContent=it.name+" · "+it.price+" oro";b.onclick=()=>buy(it);dialogActions.appendChild(b)}dialog.classList.remove("hidden")}
function interact(){let n=npcs.find(n=>Math.hypot(n.x-p.x,n.y-p.y)<85);if(!n){notify("No hay nadie cerca");return}if(n.role==="Mercader"||n.role==="Herrero"){openShop(n);return}dialogName.textContent=n.name+" · "+n.role;dialogActions.innerHTML="";if(questStage===0){dialogText.textContent="Los caminos ya no son seguros. Derrota 3 criaturas fuera de Lumen y vuelve conmigo.";questStage=1;questText.textContent="Derrota 3 criaturas";questProgress.textContent="0/3"}else if(questStage===1){dialogText.textContent="Aún debes derrotar 3 criaturas. Mantente alerta."}else if(questStage===2){dialogText.textContent="Buen trabajo. Toma esta recompensa: 60 de oro y una poción.";p.gold+=60;addItem("Poción menor","potion",1);questStage=3;questTitle.textContent="Misión completada";questText.textContent="Explora el Bosque Eterno";questProgress.textContent="✓";hud()}else dialogText.textContent="Lumen cuenta contigo, aventurero.";dialog.classList.remove("hidden")}
window.closePanels=()=>{dialog.classList.add("hidden");inventoryPanel.classList.add("hidden")};invBtn.onclick=()=>{renderInventory();inventoryPanel.classList.toggle("hidden")};interactMobile.onclick=interact;addEventListener("keydown",e=>{if(e.key.toLowerCase()==="e")interact();if(e.key.toLowerCase()==="i"){renderInventory();inventoryPanel.classList.toggle("hidden")}});renderInventory();